### ISSUE TITLE
readlink command not compatible with macOS

### ISSUE THREAD

**Issue by jeremygaither** [alexppg/kbenv#5]
The command option `readlink -f` on default macOS results in an error. Needs to use `greadlink` from the coreutils package, similar to https://github.com/little-angry-clouds/helmenv/pull/9 does.

I will see if I can work up a PR.

**Comment by alexppg** [comment]
Thanks! I can't test it since I don't own a macOS, but if you do one I'll try to ask somebody to test it for me.

**Comment by alexppg** [comment]
This should not be a problem in the new project, you may check it [here](https://github.com/little-angry-clouds/kubernetes-binaries-managers/blob/master/cmd/kbenv/README.md). If it still doesn't work as expected, please open another issue!
