### ISSUE TITLE
is it possible to get functionality to keep version per directory 

### ISSUE THREAD

**Issue by kushalgangan** [alexppg/kbenv#6]
like we have .terraform-version in tfenv so that we can have different version per directory

**Comment by alexppg** [comment]
That's actually a pretty good idea. I'll welcome any PR, but I'll try to do it myself this week anyway. Thanks!

**Comment by kushalgangan** [comment]
refer https://github.com/cunymatthieu/tgenv/blob/master/libexec/tgenv-version-file

**Comment by alexppg** [comment]
This is actually working in the new project! Check the [README](https://github.com/little-angry-clouds/kubernetes-binaries-managers/blob/master/cmd/kbenv/README.md#how-to-enforce-a-kubectl-version) @kushalgangan. If there's a bug or you'd like another thing, just open another issue! Thanks
